### PR TITLE
GameController Splitting

### PR DESCRIPTION
**Pull request by JamesAdamHughes**
Took out player and cardController from the GameController

Player is the same as before but now can call methods on it, bots are players too.
Cardcontroller handles loading and dishing out cards in one place

In prep for mocha tests

### CODE REVIEW

**Comment by BRHoward** [comment]
VERY GOOD JAMES

**Comment by JamesAdamHughes** [comment]
Local variables not being reset on adding fake answers was causing new answers to be appending to existing ones, meaning each bot submitted a card from every bot in the game.

Fixed by declaring a new random answer for each bot

**Comment by BRHoward** [comment]
looks good
@Geor23

**Comment by BRHoward** [comment]
probably not a good idea to merge this until we have the circle ci issue sorted #128

**Comment by JamesAdamHughes** [comment]
ffs

**Comment by BRHoward** [comment]
cool do it

**Pull request merged**
