### PR TITLE
User panel layout

### PR DESCRIPTION
**Pull request by JamesAdamHughes**
Just took out the user panel into a template and use ng-include to get it.
Using flex box to align the user profile next to, not on top of, the user's name

### CODE REVIEW

**Comment by BRHoward** [comment]
yep

**Comment by JamesAdamHughes** [comment]
fix issue #115

**Comment by JamesAdamHughes** [comment]
fix issue #103

**Comment by JamesAdamHughes** [comment]
@Geor23 and @BRHoward

**Comment by JamesAdamHughes** [comment]
I guess don't pull these because it will conflict with all ya'll stuff

**Comment by Geor23** [comment]
:)

**Pull request merged**
